name: card_organizer_app
description: |
  A Flutter app for organizing cards into folders using SQLite and CRUD operations. The app features:
  1. Four pre-defined folders representing the suits (Hearts, Spades, Diamonds, and Clubs).
  2. A deck of cards (1 to 13 per suit or less), and users can add cards to the appropriate folder.
  3. CRUD operations for both folders and cards.
  4. Folder limits of 3-6 cards, ensuring students implement proper logic.
  5. A user-friendly interface with lists, grids, and feedback on actions.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  path: ^1.8.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true